### ISSUE TITLE
Not recognizing anything, always showing 0.0%

### ISSUE THREAD

**Issue by bothe** [Avinash987/yogAI#1]
Nice project and work.
First time I am trying something with Flutter and came across this project.
I installed and started to use it, but it does not show any detection it seems. 
Any lead would be helpful, thanks in advance.

**Comment by Avinash987** [comment]
Thanks for trying it out, We actually trained the model with a very small data set to present a quick prototype. We are planning to improve the model's performace in the next iteration.
